import { createHash } from "node:crypto";
import { gunzipSync } from "node:zlib";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { canonicalize } from "../analysis/canonical-json.js";
import { SUPPORTED_ANALYZER } from "../analysis/contracts.js";
import { PRODUCT_VERSION } from "../product-version.js";
import { validateHtmlSnapshotProvenance, type HtmlSnapshotProvenance } from "../html-snapshot/verify.js";
import { ARCHIE_SKILLS, LOCAL_REVIEW_CLAIM, parseReleaseRecord as parseReleaseRecordV1, type ReleaseRecordV1 } from "./release-record-v1.js";

export const RELEASE_RECORD_SCHEMA_VERSION_V2 = 2 as const;
export type ReleaseArtifactV2 = {
  package: string;
  version: string;
  locator: string;
  lockIntegrity: string;
  tarballSha256: string;
  requiredPlatformPayload: string;
  dependencies: Record<string, string>;
  engines: Record<string, string>;
  binaries: Record<string, string>;
};
export interface ReleaseRecordV2 {
  schemaVersion: 2;
  product: "archie";
  version: string;
  sourceCommit: string;
  authorization: { kind: "none"; claim: typeof LOCAL_REVIEW_CLAIM };
  artifacts: [ReleaseArtifactV2, ReleaseArtifactV2];
  apm: { package: string; skills: typeof ARCHIE_SKILLS[number][]; locator: string; ref: string; resolvedCommit: string; contentHash: string };
  analyzerCompatibility: { adapter: string; typescript: string; nodeMajor: number; platform: string; architecture: string; platformPackage: string; knownDefects: string[] };
  htmlDesignSnapshot: HtmlSnapshotProvenance;
}
export interface FinalizeReleaseV2Result { record: ReleaseRecordV2; recordPath: string; receiptPath: string; recordSha256: string; }
export interface SelectedReleaseV2 { bundleDirectory: string; record: ReleaseRecordV2; recordBytes: string; recordSha256: string; artifacts: { record: ReleaseArtifactV2; tarballPath: string; tarballName: string }[]; npmLockBytes: string; }

type BundleArtifact = { package: string; version: string; locator: string; lockFile: string; tarball: string; requiredPlatformPayload: string };
type BundleInput = { format: "archie-private-bundle-input-v2"; artifacts: BundleArtifact[]; apm: { package: string; skills: string[]; locator: string; ref: string; manifest: string; lockFile: string } };
const sha256 = (bytes: string | Buffer) => createHash("sha256").update(bytes).digest("hex");
const sha512Integrity = (bytes: Buffer) => `sha512-${createHash("sha512").update(bytes).digest("base64")}`;
const object = (value: unknown, label: string): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as Record<string, unknown>; };
const text = (value: unknown, label: string): string => { if (typeof value !== "string" || !value) throw new Error(`${label} must be a non-empty string`); return value; };
const exactKeys = (value: Record<string, unknown>, keys: string[], label: string): void => { if (JSON.stringify(Object.keys(value).sort()) !== JSON.stringify([...keys].sort())) throw new Error(`${label} has unsupported or missing fields`); };
const parseJson = (bytes: string, label: string): unknown => { try { return JSON.parse(bytes); } catch { throw new Error(`${label} is not valid JSON`); } };
const isSha256 = (value: unknown): value is string => typeof value === "string" && /^[a-f0-9]{64}$/.test(value);
const skills = (value: unknown, label: string): typeof ARCHIE_SKILLS[number][] => { if (!Array.isArray(value) || JSON.stringify(value) !== JSON.stringify(ARCHIE_SKILLS)) throw new Error(`${label} must be the complete ordered Archie skill set`); return [...ARCHIE_SKILLS]; };
const map = (value: unknown, label: string): Record<string, string> => { const source = object(value, label); const result: Record<string, string> = {}; for (const key of Object.keys(source).sort()) result[key] = text(source[key], `${label}.${key}`); return result; };

function within(root: string, file: string): string { const path = resolve(root, file); if (relative(root, path).startsWith("..") || !existsSync(path) || !statSync(path).isFile()) throw new Error(`bundle artifact is missing: ${file}`); return path; }
function tarballManifest(tarball: Buffer): Record<string, unknown> {
  let archive: Buffer; try { archive = gunzipSync(tarball); } catch { throw new Error("npm tarball is not a valid gzip archive"); }
  for (let offset = 0; offset + 512 <= archive.length;) {
    const name = archive.subarray(offset, offset + 100).toString("utf8").replace(/\0.*$/, "");
    if (!name) break;
    const size = Number.parseInt(archive.subarray(offset + 124, offset + 136).toString("utf8").replace(/\0.*$/, "").trim() || "0", 8);
    if (!Number.isSafeInteger(size) || size < 0) throw new Error("npm tarball has an invalid entry size");
    if (name === "package/package.json") return object(parseJson(archive.subarray(offset + 512, offset + 512 + size).toString("utf8"), "npm tarball package manifest"), "npm tarball package manifest");
    offset += 512 + Math.ceil(size / 512) * 512;
  }
  throw new Error("npm tarball omits package/package.json");
}
function bundleInput(root: string): BundleInput {
  const value = object(parseJson(readFileSync(join(root, "bundle.json"), "utf8"), "bundle input"), "bundle input");
  exactKeys(value, ["format", "artifacts", "apm"], "bundle input");
  if (value.format !== "archie-private-bundle-input-v2") throw new Error("bundle input has an unsupported format");
  if (!Array.isArray(value.artifacts) || value.artifacts.length !== 2) throw new Error("bundle v2 must contain exactly two artifacts");
  const artifacts = value.artifacts.map((entry, index) => { const item = object(entry, `bundle artifact ${index}`); exactKeys(item, ["package", "version", "locator", "lockFile", "tarball", "requiredPlatformPayload"], `bundle artifact ${index}`); return { package: text(item.package, `bundle artifact ${index} package`), version: text(item.version, `bundle artifact ${index} version`), locator: text(item.locator, `bundle artifact ${index} locator`), lockFile: text(item.lockFile, `bundle artifact ${index} lockFile`), tarball: text(item.tarball, `bundle artifact ${index} tarball`), requiredPlatformPayload: text(item.requiredPlatformPayload, `bundle artifact ${index} requiredPlatformPayload`) }; });
  const apm = object(value.apm, "bundle APM input"); exactKeys(apm, ["package", "skills", "locator", "ref", "manifest", "lockFile"], "bundle APM input");
  return { format: "archie-private-bundle-input-v2", artifacts, apm: { package: text(apm.package, "bundle APM package"), skills: skills(apm.skills, "bundle APM skills"), locator: text(apm.locator, "bundle APM locator"), ref: text(apm.ref, "bundle APM ref"), manifest: text(apm.manifest, "bundle APM manifest"), lockFile: text(apm.lockFile, "bundle APM lockFile") } };
}
function field(textValue: string, name: string, label: string): string { const matches = [...textValue.matchAll(new RegExp(`^\\s*(?:-\\s*)?${name}:\\s*([^\\s]+)\\s*$`, "gm"))]; if (matches.length !== 1) throw new Error(`${label} must contain exactly one ${name} field`); return matches[0]![1]!; }
function skillSubset(textValue: string, header: string): string[] { const lines = textValue.replace(/\r\n/g, "\n").split("\n"); const index = lines.findIndex(line => line.trim() === `${header}:`); if (index < 0) throw new Error(`APM evidence is missing ${header}`); const values: string[] = []; for (const line of lines.slice(index + 1)) { if (/^\s*-\s+\S+\s*$/.test(line)) values.push(line.trim().slice(2)); else if (line.trim()) break; } return values; }
function apmEvidence(root: string, input: BundleInput["apm"]): ReleaseRecordV2["apm"] { const manifest = readFileSync(within(root, input.manifest), "utf8"); const lock = readFileSync(within(root, input.lockFile), "utf8"); const repo = input.locator.match(/^git@github\.com:([^/]+\/[^/]+)\.git$/)?.[1]; if (!repo) throw new Error("APM locator must be a GitHub SSH repository URL"); if (field(manifest, "git", "APM manifest") !== input.locator || field(manifest, "ref", "APM manifest") !== input.ref || JSON.stringify(skillSubset(manifest, "skills")) !== JSON.stringify(input.skills)) throw new Error("APM manifest differs from bundle input"); if (field(lock, "repo_url", "APM lock") !== repo || field(lock, "resolved_ref", "APM lock") !== input.ref || field(lock, "name", "APM lock") !== input.package || JSON.stringify(skillSubset(lock, "skill_subset")) !== JSON.stringify(input.skills)) throw new Error("APM lock differs from bundle input"); const resolvedCommit = field(lock, "resolved_commit", "APM lock"), contentHash = field(lock, "content_hash", "APM lock"); if (!/^[a-f0-9]{40}$/i.test(resolvedCommit) || !/^sha256:[a-f0-9]{64}$/i.test(contentHash)) throw new Error("APM lock evidence is malformed"); return { package: input.package, skills: input.skills as typeof ARCHIE_SKILLS[number][], locator: input.locator, ref: input.ref, resolvedCommit, contentHash }; }
function artifactEvidence(root: string, input: BundleArtifact): ReleaseArtifactV2 { if (!input.locator.startsWith("file:npm/") || input.locator.includes("..")) throw new Error("v2 artifact locators must be target-owned local tarballs"); const tarball = readFileSync(within(root, input.tarball)); const manifest = tarballManifest(tarball); if (manifest.name !== input.package || manifest.version !== input.version) throw new Error("npm tarball package identity differs from bundle input"); const lock = object(parseJson(readFileSync(within(root, input.lockFile), "utf8"), "npm lock"), "npm lock"); const packages = object(lock.packages, "npm lock packages"); const packageLock = object(packages[`node_modules/${input.package}`], `npm lock package ${input.package}`); if (packageLock.version !== input.version || packageLock.resolved !== input.locator || packageLock.integrity !== sha512Integrity(tarball)) throw new Error("npm lock evidence does not match finalized tarball bytes"); const dependencies = map(manifest.dependencies ?? {}, "artifact dependencies"), engines = map(manifest.engines ?? {}, "artifact engines"), binaries = map(manifest.bin ?? {}, "artifact binaries"); return { package: input.package, version: input.version, locator: input.locator, lockIntegrity: sha512Integrity(tarball), tarballSha256: sha256(tarball), requiredPlatformPayload: input.requiredPlatformPayload, dependencies, engines, binaries }; }
function analyzer() { return { adapter: SUPPORTED_ANALYZER.adapter, typescript: SUPPORTED_ANALYZER.typeScript, nodeMajor: SUPPORTED_ANALYZER.nodeMajor, platform: SUPPORTED_ANALYZER.platform, architecture: SUPPORTED_ANALYZER.architecture, platformPackage: SUPPORTED_ANALYZER.platformPackage, knownDefects: [...SUPPORTED_ANALYZER.knownDefects] }; }
function validateHtml(value: unknown): asserts value is HtmlSnapshotProvenance { validateHtmlSnapshotProvenance(value); const html = object(value, "release record HTML snapshot"); exactKeys(html, ["format", "upstream", "commit", "sourcePath", "gitTree", "digest", "license", "requiredNotices", "importToolVersion", "verificationCommand"], "release record HTML snapshot"); }
function validateArtifact(value: unknown, label: string): asserts value is ReleaseArtifactV2 { const artifact = object(value, label); exactKeys(artifact, ["package", "version", "locator", "lockIntegrity", "tarballSha256", "requiredPlatformPayload", "dependencies", "engines", "binaries"], label); for (const key of ["package", "version", "locator", "lockIntegrity", "requiredPlatformPayload"]) text(artifact[key], `${label}.${key}`); if (!String(artifact.locator).startsWith("file:npm/") || String(artifact.locator).includes("..") || !/^sha512-/.test(String(artifact.lockIntegrity)) || !isSha256(artifact.tarballSha256)) throw new Error(`${label} evidence is malformed`); map(artifact.dependencies, `${label}.dependencies`); map(artifact.engines, `${label}.engines`); map(artifact.binaries, `${label}.binaries`); }
export function serializeReleaseRecordV2(record: ReleaseRecordV2): string { validateRecord(record); return `${canonicalize(record)}\n`; }
function validateRecord(record: ReleaseRecordV2): void { const value = record as unknown as Record<string, unknown>; exactKeys(value, ["schemaVersion", "product", "version", "sourceCommit", "authorization", "artifacts", "apm", "analyzerCompatibility", "htmlDesignSnapshot"], "release record v2"); if (record.schemaVersion !== 2 || record.product !== "archie" || !/^[a-f0-9]{40}$/i.test(record.sourceCommit) || !record.version) throw new Error("unsupported or malformed release record v2"); const authorization = object(record.authorization, "release record authorization"); exactKeys(authorization, ["kind", "claim"], "release record authorization"); if (authorization.kind !== "none" || authorization.claim !== LOCAL_REVIEW_CLAIM) throw new Error("release record authorization must be explicit local private review only"); if (!Array.isArray(record.artifacts) || record.artifacts.length !== 2 || record.artifacts[0]?.package !== "@archie/runtime" || record.artifacts[1]?.package !== "@archie/conformance" || record.artifacts[0]?.version !== record.version || record.artifacts[1]?.version !== record.version) throw new Error("release record v2 artifacts must be ordered runtime then conformance at the product version"); const names = new Set<string>(); for (const artifact of record.artifacts) { validateArtifact(artifact, "release record artifact"); if (names.has(artifact.package)) throw new Error("release record v2 artifacts must be unique"); names.add(artifact.package); } const apm = object(record.apm, "release record APM"); exactKeys(apm, ["package", "skills", "locator", "ref", "resolvedCommit", "contentHash"], "release record APM"); if (!text(apm.package, "release record APM package") || !/^git@github\.com:[^/]+\/[^/]+\.git$/.test(text(apm.locator, "release record APM locator")) || apm.ref !== `v${record.version}` || !/^[a-f0-9]{40}$/i.test(String(apm.resolvedCommit)) || !/^sha256:[a-f0-9]{64}$/.test(String(apm.contentHash))) throw new Error("release record APM evidence is malformed"); skills(apm.skills, "release record APM skills"); const expectedAnalyzer = analyzer(); if (canonicalize(record.analyzerCompatibility) !== canonicalize(expectedAnalyzer)) throw new Error("release record has unsupported analyzer compatibility"); validateHtml(record.htmlDesignSnapshot); }
export function parseReleaseRecordV2(bytes: string): ReleaseRecordV2 { const value = object(parseJson(bytes, "release record"), "release record"); validateRecord(value as unknown as ReleaseRecordV2); if (serializeReleaseRecordV2(value as unknown as ReleaseRecordV2) !== bytes) throw new Error("release record bytes are not canonical"); return value as unknown as ReleaseRecordV2; }
/** The sole release evidence boundary used by selection and target verification. */
export function parseReleaseRecordEvidence(bytes: string): ReleaseRecordV1 | ReleaseRecordV2 { const value = parseJson(bytes, "release record"); if (object(value, "release record").schemaVersion === 2) return parseReleaseRecordV2(bytes); return parseReleaseRecordV1(bytes); }
export function selectLocalReleaseV2(directory: string): SelectedReleaseV2 {
  if (!directory || directory === "latest" || /^[a-z][a-z0-9+.-]*:\/\//i.test(directory)) throw new Error("release selection must be an explicit local directory");
  const root = resolve(directory); if (!existsSync(root) || !statSync(root).isDirectory()) throw new Error("release selection must be an existing local directory");
  validateBundleLayoutV2(root); const recordPath = join(root, "release-record-v2.json"), receiptPath = join(root, "release-review.txt");
  if (!existsSync(recordPath) || !existsSync(receiptPath)) throw new Error("release bundle is incomplete; v2 record and review receipt are required");
  const recordBytes = readFileSync(recordPath, "utf8"), record = parseReleaseRecordV2(recordBytes); if (!readFileSync(receiptPath, "utf8").includes("Archie authorization: NOT ASSESSED — locally reviewed private release selected.")) throw new Error("release bundle review receipt does not state the non-authorization boundary");
  const input = bundleInput(root); const artifacts = input.artifacts.map((inputArtifact, index) => { const artifact = record.artifacts[index]!; const tarballPath = within(root, inputArtifact.tarball), tarball = readFileSync(tarballPath); const lock = object(parseJson(readFileSync(within(root, inputArtifact.lockFile), "utf8"), "npm lock"), "npm lock"), packageLock = object(object(lock.packages, "npm lock packages")[`node_modules/${artifact.package}`], "npm lock package"); if (inputArtifact.package !== artifact.package || inputArtifact.version !== artifact.version || inputArtifact.locator !== artifact.locator || artifact.locator !== `file:npm/${tarballPath.split(/[\\/]/).pop()}` || packageLock.integrity !== artifact.lockIntegrity || packageLock.resolved !== artifact.locator || sha512Integrity(tarball) !== artifact.lockIntegrity || sha256(tarball) !== artifact.tarballSha256) throw new Error("selected bundle artifact evidence differs from its finalized record"); return { record: artifact, tarballPath, tarballName: tarballPath.split(/[\\/]/).pop()! }; });
  if (JSON.stringify(artifacts.map(artifact => artifact.record.package)) !== JSON.stringify(["@archie/runtime", "@archie/conformance"])) throw new Error("selected bundle artifacts are missing, extra, or reordered");
  const npmLockBytes = readFileSync(within(root, input.artifacts[0]!.lockFile), "utf8");
  const selectedApm = apmEvidence(root, input.apm);
  if (canonicalize(selectedApm) !== canonicalize(record.apm)) throw new Error("selected bundle APM evidence differs from its finalized record");
  return { bundleDirectory: root, record, recordBytes, recordSha256: sha256(recordBytes), artifacts, npmLockBytes };
}
export function validateBundleLayoutV2(bundleDirectory: string): void { const root = resolve(bundleDirectory); const allowed = new Set(["bundle.json", "npm", "apm", "release-record-v2.json", "release-review.txt"]); for (const entry of readdirSync(root)) if (!allowed.has(entry)) throw new Error(`bundle layout has an unsupported entry: ${entry}`); if (!existsSync(join(root, "bundle.json")) || !statSync(join(root, "bundle.json")).isFile()) throw new Error("bundle layout is missing bundle.json"); for (const required of ["npm", "apm"]) if (!existsSync(join(root, required)) || !statSync(join(root, required)).isDirectory()) throw new Error(`bundle layout is missing ${required}`); }
export function finalizeReleaseV2(request: { bundleDirectory: string; sourceCommit: string; htmlProvenancePath: string }): FinalizeReleaseV2Result { const root = resolve(request.bundleDirectory); validateBundleLayoutV2(root); if (!/^[a-f0-9]{40}$/i.test(request.sourceCommit)) throw new Error("sourceCommit must be a 40-character Git commit"); const input = bundleInput(root); if (input.apm.ref !== `v${PRODUCT_VERSION}` || input.artifacts.some(artifact => artifact.version !== PRODUCT_VERSION)) throw new Error("bundle version does not match the Archie product version authority"); const artifacts = input.artifacts.map(artifact => artifactEvidence(root, artifact)) as [ReleaseArtifactV2, ReleaseArtifactV2]; if (artifacts[0].package !== "@archie/runtime" || artifacts[1].package !== "@archie/conformance") throw new Error("bundle v2 artifacts must be ordered runtime then conformance"); const record: ReleaseRecordV2 = { schemaVersion: 2, product: "archie", version: PRODUCT_VERSION, sourceCommit: request.sourceCommit, authorization: { kind: "none", claim: LOCAL_REVIEW_CLAIM }, artifacts, apm: apmEvidence(root, input.apm), analyzerCompatibility: analyzer(), htmlDesignSnapshot: parseJson(readFileSync(request.htmlProvenancePath, "utf8"), "HTML snapshot provenance") as HtmlSnapshotProvenance }; validateHtml(record.htmlDesignSnapshot); const bytes = serializeReleaseRecordV2(record), recordSha256 = sha256(bytes); const receipt = ["Archie private release review receipt", `Product: ${record.product}@${record.version}`, `Record SHA-256: ${recordSha256}`, "Bundle layout: valid", "Artifacts: @archie/runtime, @archie/conformance", "Archie authorization: NOT ASSESSED — locally reviewed private release selected.", "This receipt reports finalized-byte consistency only. Signing, public-release trust, controller distribution, and key operations are deferred.", ""].join("\n"); const recordPath = join(root, "release-record-v2.json"); writeFileSync(recordPath, bytes); writeFileSync(join(root, "release-review.txt"), receipt); return { record, recordPath, receiptPath: join(root, "release-review.txt"), recordSha256 }; }
