import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { cp, mkdir, mkdtemp, readFile, readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import { checkArtifact } from "../skills/html-design/scripts/lib/check-artifact.mjs";
import { scaffoldArtifact } from "../skills/html-design/scripts/lib/scaffold-artifact.mjs";

const workspace = path.resolve(import.meta.dirname, "..");
const skill = path.join(workspace, "skills/html-design");
const fixtures = path.join(workspace, "test/fixtures/artifacts");
const repositoryRoot = path.resolve(workspace, "../..");

function run(script, args, cwd) {
  return spawnSync(process.execPath, [script, ...args], { cwd, encoding: "utf8", env: { PATH: process.env.PATH } });
}

function rules(report) {
  return report.diagnostics.map((item) => item.rule);
}

async function filesBelow(directory, prefix = "") {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const relative = path.posix.join(prefix, entry.name);
    if (entry.isDirectory()) files.push(...(await filesBelow(path.join(directory, entry.name), relative)));
    else files.push(relative);
  }
  return files.sort();
}

test("the skill is self-contained: no installed dependencies and bundled-package notices present", async () => {
  const files = await filesBelow(skill);
  for (const required of [
    "SKILL.md",
    "LICENSE",
    "THIRD_PARTY_NOTICES.md",
    "assets/theme.js",
    "assets/design-system.css",
    "assets/palettes/moss-paper.css",
    "templates/rail-document.html",
    "templates/review-packet.html",
    "templates/application-shell.html",
    "scripts/check-artifact.mjs",
    "scripts/scaffold-artifact.mjs",
    "scripts/apply-palette.mjs",
    "scripts/refresh-artifact-assets.mjs",
  ]) assert.ok(files.includes(required), required);
  assert.equal(files.some((file) => /(^|\/)(node_modules|package(-lock)?\.json)(\/|$)/.test(file)), false);

  const text = await readFile(path.join(skill, "SKILL.md"), "utf8");
  assert.match(text, /^---\nname: html-design\n/);
  const notices = await readFile(path.join(skill, "THIRD_PARTY_NOTICES.md"), "utf8");
  assert.match(notices, /## parse5 8\.0\.1/);
  assert.match(notices, /## entities 8\.0\.0/);

  const checker = await readFile(path.join(skill, "scripts/lib/check-artifact.mjs"), "utf8");
  assert.match(checker, /^\/\/ Generated by scripts\/bundle-html-design-checker\.mjs/);
  const bareImports = [...checker.matchAll(/^import .* from "([^"]+)";$/gm)].map((match) => match[1]).filter((specifier) => !specifier.startsWith("node:") && !specifier.startsWith("./"));
  assert.deepEqual(bareImports, []);
});

test("the committed checker bundle matches its source", () => {
  const result = spawnSync(process.execPath, ["scripts/bundle-html-design-checker.mjs", "--check"], { cwd: repositoryRoot, encoding: "utf8" });
  assert.equal(result.status, 0, result.stderr);
});

test("a copied skill scaffolds, restyles, refreshes, and checks artifacts outside the repository", async () => {
  const temporary = await mkdtemp(path.join(os.tmpdir(), "archie-html-design-portable-"));
  const installed = path.join(temporary, "skills/html-design");
  const target = path.join(temporary, "target");
  await cp(skill, installed, { recursive: true });
  await mkdir(target);

  for (const profile of ["rail-document", "application-shell", "review-packet"]) {
    const output = path.join(target, `${profile}.html`);
    const scaffold = run(path.join(installed, "scripts/scaffold-artifact.mjs"), ["--profile", profile, "--output", output], target);
    assert.equal(scaffold.status, 0, scaffold.stderr);
    const check = run(path.join(installed, "scripts/check-artifact.mjs"), [output, "--profile", profile, "--format", "json"], target);
    assert.equal(check.status, 0, check.stderr || check.stdout);
    assert.equal(JSON.parse(check.stdout).ok, true);
    assert.doesNotMatch(await readFile(output, "utf8"), /(?:src|href)=["']https?:/i);
  }

  const alternate = path.join(target, "alternate.html");
  assert.equal(run(path.join(installed, "scripts/scaffold-artifact.mjs"), ["--profile", "rail-document", "--palette", "slate-copper", "--output", alternate], target).status, 0);
  assert.match(await readFile(alternate, "utf8"), /data-ds-palette="slate-copper"/);
  assert.equal(run(path.join(installed, "scripts/apply-palette.mjs"), [alternate, "--palette", "moss-paper"], target).status, 0);
  assert.match(await readFile(alternate, "utf8"), /data-ds-palette="moss-paper"/);
  assert.equal(run(path.join(installed, "scripts/refresh-artifact-assets.mjs"), [alternate, "--palette", "slate-copper"], target).status, 0);
  assert.match(await readFile(alternate, "utf8"), /data-ds-palette="slate-copper"/);

  const invalid = path.join(target, "invalid.html");
  await writeFile(invalid, "<!doctype html><title>Invalid</title>");
  const failed = run(path.join(installed, "scripts/check-artifact.mjs"), [invalid], target);
  assert.equal(failed.status, 1);
  assert.match(failed.stdout, /document-structure|theme-metadata/);
  assert.equal(existsSync(path.join(installed, "node_modules")), false);
});

const invalidCases = [
  ["external-request.html", "external-request"],
  ["broken-link.html", "broken-internal-link"],
  ["duplicate-id.html", "duplicate-id"],
  ["heading-landmark.html", "document-structure"],
  ["missing-theme.html", "theme-metadata"],
  ["invalid-token.html", "invalid-token"],
  ["inaccessible-svg.html", "svg-accessibility"],
  ["missing-responsive.html", "profile-responsive"],
  ["missing-print.html", "profile-print"],
  ["forbidden-vocabulary.html", "forbidden-vocabulary"],
  ["source-palette.html", "source-palette"],
];

for (const [filename, expectedRule] of invalidCases) {
  test(`the checker reports ${expectedRule} with a concrete fix`, async () => {
    const report = await checkArtifact({ root: skill, file: path.join(fixtures, filename), profile: "rail-document" });
    const diagnostic = report.diagnostics.find((item) => item.rule === expectedRule);
    assert.equal(report.ok, false);
    assert.ok(diagnostic, `${filename}: ${rules(report).join(", ")}`);
    assert.ok(diagnostic.path.endsWith(filename));
    assert.ok(diagnostic.line > 0);
    assert.ok(diagnostic.fix.length > 10);
  });
}

test("the checker records a reasoned inline escape hatch and rejects an unreasoned one", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "archie-html-design-suppression-"));
  const output = path.join(directory, "brief.html");
  await scaffoldArtifact({ root: skill, profile: "rail-document", output });
  const source = await readFile(output, "utf8");
  await writeFile(output, source.replace("</head>", `  <style data-ds-check-ignore="source-palette" data-ds-check-reason="Published partner mark requires this color.">
      .partner-mark { color: #111816; }
    </style>
  </head>`));
  const report = await checkArtifact({ root: skill, file: output, profile: "rail-document" });
  assert.equal(report.ok, true, JSON.stringify(report.diagnostics, null, 2));
  assert.equal(report.suppressions.length, 1);
  assert.equal(report.suppressions[0].rule, "source-palette");

  const unreasoned = await checkArtifact({ root: skill, file: path.join(fixtures, "unreasoned-exception.html"), profile: "rail-document" });
  assert.ok(rules(unreasoned).includes("invalid-suppression"));
});
